config/routes.rb
Rails.application.routes.draw do
  resources :brands
  resources :orders
  resources :products
  resources :categories
  resources :user_types
  #get 'users/index'
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     registrations: 'users/registrations'
 }
 
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'users/:id' => 'users#edit', :via => :get, :as => :admin_edit_user
  root 'home#index'
  match '/users',   to: 'users#index',   via: 'get'
  match 'orders/by_product_id/:product_id' => 'orders#index', :via => :get, :as => :orders_by_product_id
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
    belongs_to :category
    
    scope:order_by_name, -> { order('LOWER(brand_name)') }
    scope :current, -> { where(active: true).order('LOWER(name)') }
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user

  # GET /brands or /brands.json
  def index
    @brands = Brand.all.order_by_name
  end

  # GET /brands/1 or /brands/1.json
  def show
  end

  # GET /brands/new
  def new
    @brand = Brand.new
  end

  # GET /brands/1/edit
  def edit

  end

  # POST /brands or /brands.json
  def create

    @brand = Brand.new(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully created." }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1 or /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to brand_url(@brand), notice: "Brand was successfully updated." }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1 or /brands/1.json
  def destroy
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to brands_url, notice: "Brand was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @brand = Brand.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def brand_params
      params.fetch(:brand, {}).permit(:brand_name, :category_id)
      # params.require(:category).permit(:name, :description, :bggroundimage)
    end

    def correct_user
      if current_user.user_type_id  == 1
        redirect_to root_path, notice: "Not authorised"
      end
    end 

    private
    def set_brand
      @brand = Brand.find(params[:id])
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/views/brands/_form.html.erb
<%= form_with(model: brand) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
        <% brand.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label "Name *", class:"form-label leftmargin" %>
    <%= form.text_field :brand_name, class:"form-control leftmargin edituserwidth" %>
  </div>

     <div class="field">
    <%= form.label :category, class:"form-label leftmargin" %><br/>
      <%= form.select :category_id, options_for_select(Category.all.current.collect { |p| [ p.name, p.id ] }, :selected=>brand.category_id), 
  {}, { class: "form-select leftmargin edituserwidth" } %>  
  </div>
<br/>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary leftmargin" %>
  </div>

<% end %>

app/views/brands/edit.html.erb
<br/>
<div class="container">
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>
<%= link_to 'Back', brands_path, class:"btn btn-secondary leftmargin"  %>
</div>

app/views/brands/index.html.erb
<div class="container">

<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Category</th>
      <th>Active</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.brand_name %></td>
         <td><%= brand.category.name %></td>
        <td><%= brand.active %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand), class:"btn btn-sm btn-outline-secondary" %></td>
        <% if brand.active? %>
        <td><%= link_to 'Delete', brand, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-outline-danger" %></td>
        <% else %>
        <td><%= link_to 'Un-Delete', brand, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-outline-secondary" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path, class:"btn btn-secondary"  %>

</div>

app/views/brands/new.html.erb
<div class="container">
  <div class="card">
  <div class="card-header">
<h4>New Brand</h4>
</div>
<br/>
<%= render 'form', brand: @brand %> 
<br/>
 </div>
</div>

app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>