config/routes.rb
Rails.application.routes.draw do
  resources :brands
  resources :orders
  resources :products
  resources :categories
  resources :user_types
  #get 'users/index'
   devise_for :users, controllers: {
     sessions: 'users/sessions',
     registrations: 'users/registrations'
 }
 
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user
  match 'users/:id' => 'users#edit', :via => :get, :as => :admin_edit_user
  root 'home#index'
  match '/users',   to: 'users#index',   via: 'get'
  match 'orders/by_product_id/:product_id' => 'orders#index', :via => :get, :as => :orders_by_product_id
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :brand
    #belongs_to :user
    has_many :product_comments
    has_many :orders
    scope :current, -> { where(active: true).order('LOWER(name)') }
    scope:order_by_name, -> { order('LOWER(name)') }
    has_many_attached :images
    validates :name, presence: true
    validates :stock, presence: true
    validates :price, presence: true
    validate :image_type
    def thumbnail input
          self.images[input].variant(resize: "300x300").processed
    end

    private
    def image_type
        if images.attached? == false
            errors.add(:images, "are missing")
        end
        images.each do |image|
            if !image.content_type.in?(%('image/jpeg' 'image/png'))
                errors.add(:images, "needs to be JPEG or PNG")
            end
        end
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user
  # GET /products or /products.json
  def index
    @products = current_user.products.current
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
    # category = Category.new
    # category.name = "-SELECT-"
    # category.id = -1
    # @product = Category.all.current.insert(0,category)
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    respond_to do |format|
      if @product.save
        product = current_user.products.find_by_name(product_params[:name])
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    if current_user.user_type_id  == 1
      redirect_to root_path, notice: "Not authorised"
    end
  end 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, :brand, :stock, :active, :category_id, :price, images: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <%= form.label :category, class:"form-label leftmargin" %><br/>
      <%=  form.select :category_id, 
    options_for_select(Category.all.current.collect { |p| [ p.name, p.id ] }), 
    {include_blank: true}, 
    { class: "form-select leftmargin edituserwidth", onchange: "alert('chandan')" } %>  
  </div>

    <div class="field">
    <%= form.label :brand, class:"form-label leftmargin" %><br/>
      <%=  form.select :brand_id, 
    options_for_select(Category.all.current.collect { |p| [ p.name, p.id ] }, 
    :selected=>product.category_id), 
    {include_blank: true}, 
    { class: "form-select leftmargin edituserwidth", onchange: "alert('chandan')" } %>  
  </div>

  <div class="field">
    <%= form.label :name, class:"form-label leftmargin" %>
    <%= form.text_field :name, class:"form-control leftmargin edituserwidth" %>
  </div>

  <div class="field">
    <%= form.label :description, class:"form-label leftmargin" %>
    <%= form.text_area :description, rows:"5", class:"form-control leftmargin edituserwidth" %>
  </div>

  <div class="field">
    <%= form.label :price, class:"form-label leftmargin" %>
    <%= form.number_field :price, step: :any, class:"form-control leftmargin edituserwidth" %>
  </div>

  <div class="field">
    <%= form.label :stock, class:"form-label leftmargin" %>
    <%= form.number_field :stock, class:"form-control leftmargin edituserwidth" %>
  </div>
<br/>
    <div class="field leftmargin">
    <%= form.label "Photos", class:"form-label" %><br />
     <%= form.file_field :images, multiple: true, class:"form-control edituserwidth" %>
  </div>

<br/>
  <div class="actions">
    <%= form.submit class:"btn btn-secondary leftmargin" %>
    <%= link_to 'Back', :back, class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/products/_products_grid.html.erb
<table class="table table-striped table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Brand</th>
       <th>Category</th>
        <th>Sold</th>
      <th>Stock</th>
      <th>Price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% resource.products.current.each do |product| %>
      <tr>
        <td><%= link_to product.name, product %></td>
        <td><%= product.brand %></td>
         <td><%= product.category.name %></td>
         <% if product.orders.where(active: true).count > 0 %>
        <td><%= link_to product.orders.where(active: true).count, orders_by_product_id_path(product.id) %></td>
        <% else %>
        <td>0</td>
        <% end %>
        <td><%= product.stock %></td>
        <td><%= product.price %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class:"btn btn-sm btn-outline-secondary" %></td>
        <td><%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-outline-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/edit.html.erb
<br/>
<div class="container">
<h4>Editing Product</h4>

<%= render 'form', product: @product %>
</div>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Brand</th>
      <th>Price</th>
      <th>Stock</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.brand %></td>
        <td><%= product.price %></td>
        <td><%= product.stock %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<br/>
<div class="container">
  <div class="card">
  <div class="card-header">
<h4>New Product</h4>
</div>
<br/>
<%= render 'form', product: @product %>
<br/>
 </div>
 <br/>
</div>

app/views/products/show.html.erb
<br/>
<div class="container jumbotron">

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @product.brand %>
</p>
<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>
<p>
  <strong>Category:</strong>
  <%= @product.category.name %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @product.stock %>
</p>

<p>
  <strong>Images:</strong>
  <% (0...@product.images.count).each do |image| %>
    <%= image_tag(@product.thumbnail(image), class:"img-fluid img-thumbnail")  %>
  <% end %>
</p>

<p>
  <strong>Active:</strong>
  <%= @product.active %>
</p>


<%= link_to 'Edit', edit_product_path(@product), class:"btn btn-secondary" %>  <%= link_to 'Back', :back, class:"btn btn-secondary" %>
</div>